name = "LexiconMining"
uuid = "d7cc8c4b-a12f-4850-86db-026797cdfce2"
authors = ["Neel Smith  <dnsmith.neel@gmail.com>"]
version = "0.1.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
PolytonicGreek = "72b824a7-2b4a-40fa-944c-ac4f345dc63a"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"

[compat]
EzXML = "1"
PolytonicGreek = "0.14"
SplitApplyCombine = "1"